### ISSUE TITLE
Commit d770570 (Move content to folder based on years) broke many links

### ISSUE THREAD

**Issue by 0xced** [dotnet/designs#106]
I found [three ][1] [broken][2] [links][3] because of commit d7705707df9338b3ce1a95623abb3891069f51ff, just today!

Unfortunately, not many people are aware of the GitHub feature that allow you to [get a permalink to a file in a specific commit][4].

I just wanted to bring this to your attention for you to consider next time you move files around in a repository.

[1]: https://github.com/dotnet/runtime/issues/11201#issuecomment-555437980
[2]: https://github.com/dotnet/runtime/issues/3734#issuecomment-522817605
[3]: https://github.com/microsoft/azure-pipelines-tasks/issues/6119#issuecomment-381753790
[4]: https://help.github.com/en/github/managing-files-in-a-repository/getting-permanent-links-to-files#press-kbdykbd-to-permalink-to-a-file-in-a-specific-commit

**Comment by terrajobst** [comment]
Hey @0xced 

Yeah, this is an issue with GitHub all up. We are generally more disciplined when it comes to the source code repos. Repos like these haven't had a good structure at the start which is why it was time to establish this now as we've started using this repo more and more. Sorry about that :-(

**Comment by dagood** [comment]
This happened to me too. 😢 https://github.com/dotnet/core/issues/3303, and I'm sure more that I don't know about.

Was it considered to use a new dir name for the new structure and change the content of all files in `accepted` to point to their new locations? But... too late for that, unless we're ok having two copies of all the files (to accommodate new links since the first move happened)?

Pinning links (pressing <kbd>y</kbd>) is a defensive measure I use for code, but generally not for docs, because I don't want to prevent people from seeing revisions. Would you recommend using it for this repo or is the structure set in stone now and I should be safe?
